AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'Deploys a Lambda function to process processed data'

Parameters:

  SourceSystemName:
    Type: String
    Description: 'The name of the source system to ingest (3-15 lowercase characters)'
    AllowedPattern: '^[a-z]{3,15}$'

  StageName:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    Description: 'The stage of deployment'

  PublicKey:
    Type: String
    Default: 'None'
    Description: 'The upstream public key of the processed for verifying incoming manifests'

Resources:

  IngestLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${StageName}-${SourceSystemName}-processed-lambda-function'
      Handler: 'com.aws.ingest.lambda.processed.ProcessedLambda'
      Runtime: java8
      Timeout: 900
      MemorySize: 1024
      CodeUri: ../target/IngestPipeline-1.0.0.jar
      Role:
        Fn::ImportValue:
          !Sub '${StageName}-${SourceSystemName}-processed-lambda-role-arn'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 1
            Enabled: true
            Queue: !GetAtt 'ProcessedBucketQueue.Arn'
      Environment:
        Variables:
          CONFIG_BUCKET:
            Fn::ImportValue:
              !Sub '${StageName}-${SourceSystemName}-s3-processed-bucket'
          PUBLIC_KEY: !Sub '${PublicKey}'

  ProcessedBucketQueue:
    Type: AWS::SQS::Queue
    Properties:
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      QueueName: !Sub '${StageName}-processed-${SourceSystemName}-queue'
      VisibilityTimeout: 960
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessedBucketRedriveQueue.Arn
        maxReceiveCount: 5

  ProcessedBucketRedriveQueue:
    Type: AWS::SQS::Queue
    Properties:
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      QueueName: !Sub '${StageName}-processed-${SourceSystemName}-redrive-queue'
      VisibilityTimeout: 960

  ProcessedBucketQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt 'ProcessedBucketQueue.Arn'
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn:
        Fn::ImportValue:
          !Sub '${StageName}-${SourceSystemName}-sns-processed-topic-arn'

  ProcessedBucketQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ProcessedBucketQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: sqs:SendMessage
          Resource: "*"
          Condition:
            ArnEquals:
              aws:SourceArn:
                Fn::ImportValue:
                  !Sub '${StageName}-${SourceSystemName}-sns-processed-topic-arn'
